/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeckNewRouteImport } from './routes/deck/new'
import { Route as DeckIdRouteImport } from './routes/deck/$id'
import { Route as DeckIdPrintRouteImport } from './routes/deck/$id/print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckNewRoute = DeckNewRouteImport.update({
  id: '/deck/new',
  path: '/deck/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdRoute = DeckIdRouteImport.update({
  id: '/deck/$id',
  path: '/deck/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckIdPrintRoute = DeckIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => DeckIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/new': typeof DeckNewRoute
  '/deck/$id/print': typeof DeckIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/new': typeof DeckNewRoute
  '/deck/$id/print': typeof DeckIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$id': typeof DeckIdRouteWithChildren
  '/deck/new': typeof DeckNewRoute
  '/deck/$id/print': typeof DeckIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/deck/$id' | '/deck/new' | '/deck/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/deck/$id' | '/deck/new' | '/deck/$id/print'
  id: '__root__' | '/' | '/deck/$id' | '/deck/new' | '/deck/$id/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckIdRoute: typeof DeckIdRouteWithChildren
  DeckNewRoute: typeof DeckNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/new': {
      id: '/deck/new'
      path: '/deck/new'
      fullPath: '/deck/new'
      preLoaderRoute: typeof DeckNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id': {
      id: '/deck/$id'
      path: '/deck/$id'
      fullPath: '/deck/$id'
      preLoaderRoute: typeof DeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$id/print': {
      id: '/deck/$id/print'
      path: '/print'
      fullPath: '/deck/$id/print'
      preLoaderRoute: typeof DeckIdPrintRouteImport
      parentRoute: typeof DeckIdRoute
    }
  }
}

interface DeckIdRouteChildren {
  DeckIdPrintRoute: typeof DeckIdPrintRoute
}

const DeckIdRouteChildren: DeckIdRouteChildren = {
  DeckIdPrintRoute: DeckIdPrintRoute,
}

const DeckIdRouteWithChildren =
  DeckIdRoute._addFileChildren(DeckIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckIdRoute: DeckIdRouteWithChildren,
  DeckNewRoute: DeckNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
